---
title: "R Notebook"
output: html_notebook
---


---
title: "Prepare Data"
---

Summary: This code prepares the datasets needed to replicate. This file requires: 

(1) Obtaining the original NARA records. 
(2) Obtaining the 1940 Census
(3) Obtaining the BUNMD file 
(4) Obtaining the CenSoc-Numident (V2) file 

The resulting output files are available elsewhere. 

```{r}
## library packages 
library(data.table)
library(tidyverse)
```


```{r}
## read in all applications 
applications <- fread("/censoc/data/numident/2_numident_files_cleaned/apps_cleaned.csv")

## Set "Missing"" to NA 
applications[race == 0, race := NA]
applications[race == 9, race := NA]

## Removing missing races and only look at post-1980 applications
ss5_applications_post_1980 <- applications %>% 
  filter(!is.na(race)) %>% 
  filter(year_cycle >= 1983)

## Identify individuals with more than one application
setDT(ss5_applications_post_1980)
ss5_applications_post_1980[, number_of_distinct_apps:=.N, by = ssn]
```

```{r}
numident <- fread("/censoc/data/censoc_linked_with_census/1940_v2/censoc_numident_v2_linked_with_census.csv")

numident <- numident %>% 
  left_join(ss5_applications_post_1980 %>% select(ssn, number_of_distinct_apps))
```
```{r}
numident <- numident %>% 
  mutate(multiple_apps = case_when(
    number_of_distinct_apps == 1 | is.na(number_of_distinct_apps) ~ "no",
    TRUE ~ "yes"
  ))

numident <- numident %>% 
  censocdev::recode_education(educ_var = EDUC)


numident_select <- numident %>% 
  filter(byear %in% 1901:1927) %>% 
  filter(INCWAGE %in% 1:5001) %>% 
  filter(AGE >= 18)

  group_by(multiple_apps) %>% 
  summarize(median(INCWAGE, na.rm = T), n())

model <- lm(educ_yrs ~ multiple_apps + as.factor(byear), data = numident)
```

```{r}
numident %>% 
  filter(byear %in% 1901:1927) %>% 
  filter(AGE >= 18) %>% 
  group_by(multiple_apps) %>% 
  summarize(mean(educ_yrs, na.rm = T), mean(dyear))



```


```{r}
fix_results <- fixest::feols(educ_yrs ~ multiple_apps | byear, data = numident_select)

fix_results_incwage <- fixest::feols(INCWAGE ~ multiple_apps | byear, data = numident_select)

```


