---
title: "Social Status Indicators"
---

Summary: In this notebook, we explore the association between early life social status indicators and shifts in racial self-identification. 

```{r}
## library packages
library(tidyverse)
library(data.table)
library(stargazer)
library(broom)
library(ggsci)
library(cowplot)
library(here)
```


```{r}
numident_with_covariates <- fread(here("data/numident_dataset_with_covariates.csv")) %>% 
  filter(year_cycle_first > 1983) %>% 
  filter(byear %in% c(1901:1927)) %>% 
  filter(race_last_cyear %in% c(1984:2007)) %>% 
  mutate(time_between_apps = year_cycle_last - year_cycle_first)
```


## Descriptives (Association)

```{r}
## calculate mean education 
education_data <- numident_with_covariates %>% 
  filter(AGE >= 18) %>% 
  #filter(byear < 1925) %>% 
  #filter(SEX == 1) %>% 
 filter(link_abe_exact_conservative == 1) %>% 
  mutate(race = case_when(
    race_first == 1  ~ "White",
    race_first == 2  ~ "Black",
    race_first == 4 ~ "Asian",
    race_first == 5  ~ "Hispanic",
    race_first == 6 ~ "American Indian",
    TRUE ~ "other")) %>% 
  mutate(last = case_when(
    race_last == 1 ~ "Shift to a White identification",
    TRUE ~ "No Shift"
  )) %>% 
  group_by(race, last) %>% 
  summarize(mean = mean(educ.yrs, na.rm = T),
         se=sd(educ.yrs, na.rm = T)/sqrt(n()),
         n = n())
  
## White educational attainment 
white_educ_attainment <- education_data %>% 
  ungroup() %>% 
  filter(race == "White" & last == "Shift to a White identification") %>% 
  select(mean) %>% 
  as.double()

## plot education 
educ_plot <- education_data %>% 
  filter(race != "White") %>% 
  filter(race != "other") %>% 
  ggplot(aes(x = race,
             y = mean,
             ymin = mean - 1.96*se,
             ymax = mean + 1.96*se,
             group = last, 
             color = last,
             shape = last)) +
  geom_pointrange(position = position_dodge(width = .25)) + 
  geom_hline(yintercept = white_educ_attainment, lwd = .7, lty = 2, color = "black") + 
  annotate("text", x=3.5, y = white_educ_attainment+.63, label= "Always White", size = 3) +
  coord_flip() + 
  theme_cowplot() +
  background_grid() + 
  labs(title = "",
       x = "Initial Ethnoracial Category", 
       y = "Educational Attainment (Years)") + 
  theme(legend.position = "bottom", 
        legend.title=element_blank()) + 
  scale_color_lancet() +
ylim(6, 12)
```

```{r}
## calculate mean income wage
income_data <- numident_with_covariates %>% 
  filter(INCWAGE > 0 & INCWAGE < 5003) %>% 
  filter(AGE >= 18) %>% 
 # filter(sex == 1) %>% 
  mutate(race = case_when(
    race_first == 1  ~ "White",
    race_first == 2  ~ "Black",
    race_first == 4 ~ "Asian",
    race_first == 5  ~ "Hispanic",
    race_first == 6 ~ "American Indian",
    TRUE ~ "other")) %>% 
  mutate(last = case_when(
    race_last == 1 ~ "Shift to a White identification",
    TRUE ~ "No Shift"
  )) %>% 
  group_by(race, last) %>% 
  summarize(mean = mean(INCWAGE, na.rm = T),
         se=sd(INCWAGE, na.rm = T)/sqrt(n()))
  
## White educational attainment 
white_income_data <- income_data %>% 
  ungroup() %>% 
  filter(race == "White" & last == "Shift to a White identification") %>% 
  select(mean) %>% 
  as.double()

income_plot <- income_data %>% 
  filter(race != "White") %>% 
  filter(race != "other") %>% 
  ggplot(aes(x = race,
             y = mean,
             ymin = mean - 1.96*se,
             ymax = mean + 1.96*se,
             group = last, 
             color = last,
             shape = last)) +
  geom_pointrange(position = position_dodge(width = .25)) + 
  geom_hline(yintercept = white_income_data, lwd = .7, lty = 2, color = "black") + 
  annotate("text", x=3.5, y = white_income_data + 65, label= "Always White", size = 3) +
  coord_flip() + 
  theme_cowplot() +
  background_grid() + 
  labs(title = "",
       x = "Initial Ethnoracial Category", 
       y = "Wage and Salary Income") + 
  theme(legend.position = "none") + 
  scale_color_lancet()

legend <- get_legend(
  # create some space to the left of the legend
  educ_plot + 
    guides(color = guide_legend(nrow = 1)) +
    theme(legend.position = "bottom")
)

bivariate_correlations <- cowplot::plot_grid(
  income_plot + theme(legend.position="none"),
  educ_plot + theme(legend.position="none"),
  labels = c("a", "b"),
  ncol = 1)

bivariate_correlations_plot <- plot_grid(bivariate_correlations, legend, ncol = 1, rel_heights = c(1, .1))


ggsave(plot = bivariate_correlations_plot, filename = here("figures/bivariate_correlations.png"), height = 13, width = 7)
```

## Logistic Regressions

```{r}
## create dummy variables
numident_with_covariates <- numident_with_covariates %>% 
  mutate(change_to_white = case_when(
    race_first != 1 & race_last == 1 ~ 1,
    TRUE ~ 0
  )) %>% 
     mutate(change_from_white = case_when(
    race_first == 1 & race_last != 1 ~ 1,
    TRUE ~ 0
  )) 
```

```{r}
## create income dataset (18+, birth cohorts 1901-1927) 
income_data <- numident_with_covariates %>% 
  filter(byear %in% 1901:1927) %>% 
  filter(AGE >= 18) %>% 
  filter(INCWAGE > 0 & INCWAGE < 5002) %>% 
  mutate(black = case_when(race_first == 2 ~ 1, TRUE ~ 0)) %>% 
  mutate(other = case_when(race_first == 3 ~ 1, TRUE ~ 0)) %>% 
  mutate(asian = case_when(race_first == 4 ~ 1, TRUE ~ 0)) %>% 
  mutate(hispanic = case_when(race_first == 5 ~ 1, TRUE ~ 0)) %>% 
  mutate(north.american.native = case_when(race_first == 6 ~ 1, TRUE ~ 0)) %>% 
  mutate(woman = case_when(sex == 2 ~ 1, TRUE ~ 0)) %>% 
  mutate(income.wage.dollars = INCWAGE/1000)

## income and education models 
ed.inc.hispanic <- glm(change_to_white ~ educ.yrs + income.wage.dollars + woman  + as.factor(byear), family = "binomial", data = subset(income_data, hispanic == 1))
ed.inc.black <- glm(change_to_white ~ educ.yrs + income.wage.dollars + woman + as.factor(byear), family = "binomial", data = subset(income_data, black == 1))
ed.inc.indian <- glm(change_to_white ~  educ.yrs + income.wage.dollars + woman + as.factor(byear), family = "binomial", data = subset(income_data, north.american.native == 1))
ed.inc.asian <- glm(change_to_white ~  educ.yrs + income.wage.dollars + woman + as.factor(byear), family = "binomial", data = subset(income_data, asian == 1))

## income models 
inc.hispanic <- glm(change_to_white ~ income.wage.dollars + woman  + as.factor(byear), family = "binomial", data = subset(income_data, hispanic == 1))
inc.black <- glm(change_to_white ~ income.wage.dollars + woman + as.factor(byear), family = "binomial", data = subset(income_data, black == 1))
inc.indian <- glm(change_to_white ~  income.wage.dollars + woman + as.factor(byear), family = "binomial", data = subset(income_data, north.american.native == 1))
inc.asian <- glm(change_to_white ~income.wage.dollars + woman + as.factor(byear), family = "binomial", data = subset(income_data, asian == 1))

## education data 
education_data <- numident_with_covariates %>% 
  filter(byear %in% 1901:1927) %>% 
  filter(AGE >= 18) %>% 
  mutate(black = case_when(race_first == 2 ~ 1, TRUE ~ 0)) %>% 
  mutate(other = case_when(race_first == 3 ~ 1, TRUE ~ 0)) %>% 
  mutate(asian = case_when(race_first == 4 ~ 1, TRUE ~ 0)) %>% 
  mutate(hispanic = case_when(race_first == 5 ~ 1, TRUE ~ 0)) %>% 
  mutate(north.american.native = case_when(race_first == 6 ~ 1, TRUE ~ 0)) %>% 
  mutate(woman = case_when(sex == 2 ~ 1, TRUE ~ 0))

## education models 
ed.hispanic <- glm(change_to_white ~ educ.yrs + woman + as.factor(byear), family = "binomial", data = subset(education_data, hispanic == 1))
ed.black <- glm(change_to_white ~ educ.yrs + woman + as.factor(byear), family = "binomial", data = subset(education_data, black == 1))
ed.indian <- glm(change_to_white ~ educ.yrs + woman + as.factor(byear), family = "binomial", data = subset(education_data, north.american.native == 1))
ed.asian <- glm(change_to_white ~ educ.yrs + woman + as.factor(byear),  family = "binomial", data = subset(education_data, asian == 1))

## output stargazer table (log odds; exponentiate to get log odds)
## https://stackoverflow.com/questions/16236560/odds-ratios-instead-of-logits-in-stargazer-latex-output/63789273#63789273

# 
# regression_table <- stargazer(inc.hispanic, inc.black, inc.indian, inc.asian, ed.hispanic, ed.black, ed.indian, ed.asian, ed.inc.hispanic, ed.inc.black, ed.inc.indian, ed.inc.asian, 
#           type = "latex", digits = 3, keep = c("income.wage.dollars", "educ.yrs", "woman"), style = "demography", 
#           font.size = "small",
#           # omit.stat=c("f", "rsq"),
#           column.sep.width = "-5pt",
#           column.labels = c("Wage Income", "Education", "Wage income and Education"),
#           column.separate = c(4, 4, 4),
#           title = "Linear Regression Models Predicting a Shift From a Non-White Identification Towards a White Identification", 
#           apply.coef=exp, t.auto=F, p.auto=F, report = "vct*") 
```

```{r}
## run education models 
education_coefficients <- education_data %>%
  mutate(race = case_when(
    race_first == 1  ~ "White",
    race_first == 2  ~ "Black",
    race_first == 4  ~ "Asian",
    race_first == 5  ~ "Hispanic",
    race_first == 6  ~ "American Indian",
    TRUE ~ "other")) %>% 
  filter(race %in% c("Black", "Asian", "Hispanic", "American Indian")) %>% 
  filter(byear %in% 1901:1927) %>% 
  filter(AGE >= 18) %>% 
  group_by(race) %>%
  do(tidy(glm(change_to_white ~ educ.yrs + woman + as.factor(byear), family = "binomial", data = .))) %>% 
  filter(term %in% c("educ.yrs")) %>% 
  mutate(estimate_odds = exp(estimate),
         low = exp(estimate - 1.96*std.error),
         upper = exp(estimate + 1.96*std.error))

## education coefficients 
education_coefficients %>% 
  ggplot() + 
  geom_pointrange(aes(x = race, y = estimate_odds, ymin = low, ymax = upper)) + 
  theme_minimal(20) + 
  geom_hline(yintercept = 1, linetype = "dashed") + 
  coord_flip()

## income coefficients 
income_coefficients <- income_data %>%
  mutate(race = case_when(
    race_first == 1  ~ "White",
    race_first == 2  ~ "Black",
    race_first == 4  ~ "Asian",
    race_first == 5  ~ "Hispanic",
    race_first == 6  ~ "American Indian",
    TRUE ~ "other")) %>% 
  filter(race %in% c("Black", "Asian", "Hispanic", "American Indian")) %>% 
  filter(byear %in% 1901:1927) %>% 
  filter(AGE >= 18) %>% 
  filter(income.wage.dollars > 0 & income.wage.dollars < 5010) %>% 
  group_by(race) %>%
  do(tidy(glm(change_to_white ~ income.wage.dollars + woman + as.factor(byear), family = "binomial", data = .))) %>% 
  filter(term %in% c("income.wage.dollars")) %>% 
  mutate(estimate_odds = exp(estimate),
         low = exp(estimate - 1.96*std.error),
         upper = exp(estimate + 1.96*std.error)) 

## income model bind rows 
odds_ratios <- bind_rows(education_coefficients, income_coefficients) %>% 
  mutate(term = case_when(
    term == "educ.yrs" ~ "Education",
    term == "income.wage.dollars" ~ "Wage Income"
  )) %>% 
  ggplot() + 
  geom_pointrange(aes(x = race, y = estimate_odds, ymin = low, ymax = upper)) + 
  theme_cowplot(18) + 
  background_grid() + 
  geom_hline(yintercept = 1, linetype = "dashed") + 
  coord_flip() + 
  facet_wrap(~term, scales = "free", nrow = 1)+ 
  labs(y = "Odds Ratio",
       x = "Initial Ethnoracial Category"
  )

ggsave(plot = odds_ratios, filename = here("figures/odds_ratio.png"), height = 6, width = 13)
```




