---
title: "Prepare Data"
---

Summary: This code prepares the datasets needed to replicate. This file requires: 

(1) Obtaining the original NARA records. 
(2) Obtaining the 1940 Census
(3) Obtaining the BUNMD file 
(4) Obtaining the CenSoc-Numident (V2) file 

The resulting output files are available elsewhere. 

```{r}
## library packages 
library(data.table)
library(tidyverse)
```


```{r}
## read in all applications 
applications <- fread("/censoc/data/numident/2_numident_files_cleaned/apps_cleaned.csv")

## Set "Missing"" to NA 
applications[race == 0, race := NA]
applications[race == 9, race := NA]

## Removing missing races and only look at post-1980 applications
ss5_applications_post_1980 <- applications %>% 
  filter(!is.na(race)) %>% 
  filter(year_cycle >= 1980)

## Identify individuals with more than one application
setDT(ss5_applications_post_1980)
ss5_applications_post_1980[, number_of_distinct_apps:=.N, by = ssn]

## Identify multiple apps with 2 or more post 1980 (new racial codes) 
post_1980_multiple_apps <- ss5_applications_post_1980 %>% 
  filter(number_of_distinct_apps >= 2)

## Identify SSN and first and last app with cycle date
race_first <- post_1980_multiple_apps %>%
  mutate(cycle = year_cycle + (month_cycle/12)) %>% 
  group_by(ssn) %>%
  filter(cycle == min(cycle)) %>% 
  select(year_cycle_first = year_cycle, race_first = race, ssn, form_signer_first = form_signer) %>% 
  ungroup()

race_last <- post_1980_multiple_apps %>%
  mutate(cycle = year_cycle + (month_cycle/12)) %>% 
  group_by(ssn) %>%
  filter(cycle == max(cycle)) %>% 
  select(year_cycle_last = year_cycle, race_last = race, ssn, form_signer_last = form_signer) %>% 
  ungroup()

individuals_2plus_apps <- race_first %>% 
  left_join(race_last, by = "ssn") %>% 
  ungroup() %>% 
  distinct(ssn, .keep_all = T)
```

Add BUNMD covariates 

```{r}
## read in bunmd 
bunmd <- fread("/censoc/data/censoc_v2/bunmd_v2.csv")

analysis_dataset <- inner_join(individuals_2plus_apps, 
                               bunmd %>% 
                                 select(-race_first, -race_last), by = "ssn")
```

Add matched census files 

```{r}
## CenSoc-Numident ABE
matched_census_bunmd <- fread("/home/ipums/wontak.joo-ipums/project/abe/data/matched-1940-census-bunmd/matched_census_bunmd.csv") %>% 
  mutate(link_abe_exact_conservative = case_when(
    uniquestub_match2 == 1 & uniquestub_file2 ~ 1,
     TRUE ~ 0))

## Matched data 
analysis_dataset_with_covariates <- analysis_dataset %>% 
  inner_join(matched_census_bunmd %>% 
               select(HISTID = id_A, id_B, link_abe_exact_conservative), by = c("ssn" = "id_B"))

## read in census
census_1940 <- fread("/ipums-repo2019/1940/TSV/P.tsv", select = c("HISTID", "INCWAGE", "EDUC", "OCCSCORE", "AGE", "RACE"))

## add covariates
analysis_dataset_with_covariates <- census_1940 %>% 
  inner_join(analysis_dataset_with_covariates) 

## create eduation variable
analysis_dataset_with_covariates <- analysis_dataset_with_covariates %>% 
  mutate(educ.yrs = case_when(
  EDUC == 2 ~ 0,
  EDUC == 14 ~ 1,
  EDUC == 15 ~ 2,
  EDUC == 16 ~ 3,
  EDUC == 17 ~ 4,
  EDUC == 22 ~ 5,
  EDUC == 23 ~ 6,
  EDUC == 25 ~ 7,
  EDUC == 26 ~ 8,
  EDUC == 30 ~ 9,
  EDUC == 40 ~ 10,
  EDUC == 50 ~ 11,
  EDUC == 60 ~ 12,
  EDUC == 70 ~ 13,
  EDUC == 80 ~ 14,
  EDUC == 90 ~ 15,
  EDUC == 100 ~ 16,
  EDUC == 110 ~ 17
))

## write out files 
fwrite(analysis_dataset_with_covariates, "../../data/numident_dataset_with_covariates.csv")

fwrite(analysis_dataset, "../../data/numident_dataset.csv")
```
